config/routes.rb
Rails.application.routes.draw do
  resources :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end
  def new
    @picture = Picture.new
  end
  def create
    Picture.create(picture_params)
    redirect_to new_picture_path
  end
  def show
    @picture = Picture.find(params[:id])
  end
  def edit
    @picture = Picture.find(params[:id])
  end
  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "pictureを編集しました！"
    else
      render :edit
    end
  end
  private
  def picture_params
    params.require(:picture).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApplication1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/edit.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_title">
    <%= form.label :content%>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures一覧</h1>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.title %></td>
    <td><%= picture.content %></td>
    <td><%= link_to '詳細を確認する' , picture_path(picture.id) %></td>
    <td><%= link_to 'pictureを編集する', edit_picture_path(picture.id) %></td>
  </tr>
  <% end %>
</table>
<br>
<%= link_to '新しくpictureを投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_title">
    <%= form.label :content%>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/show.html.erb
<h1>picture詳細画面</h1>
<p>タイトル: <%= @picture.title %></p>
<p>内容: <%= @picture.content %></p>